# Generated by Django 5.0.2 on 2024-05-15 02:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProject',
            fields=[
                ('nomp', models.CharField(max_length=50, null=True)),
                ('geomp', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('descp', models.TextField(null=True)),
                ('debutp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('finp', models.DateTimeField(null=True)),
                ('cityp', models.CharField(max_length=255, null=True)),
                ('piece_joinde', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('locationp', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
                ('polygon_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('clientp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('supervisorp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='cage',
            fields=[
                ('Idcage', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('centre', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('latitude_centre', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude_centre', models.CharField(blank=True, max_length=50, null=True)),
                ('cage_range', models.BigIntegerField(blank=True, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('polyg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.myproject')),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('Idnode', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('node_range', models.BigIntegerField(blank=True, null=True)),
                ('Sensors', models.CharField(max_length=50, null=True)),
                ('RSSI', models.BigIntegerField(null=True)),
                ('Battery_value', models.BigIntegerField(null=True)),
                ('detection', models.BigIntegerField(null=True)),
                ('cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.cage')),
                ('polyg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.myproject')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdData', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('distance', models.FloatField(default=0, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='users.node')),
            ],
        ),
        migrations.CreateModel(
            name='parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(blank=True, max_length=50, null=True)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='users.myproject')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='parc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.parcelle'),
        ),
        migrations.AddField(
            model_name='cage',
            name='parc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.parcelle'),
        ),
    ]
