# Generated by Django 4.1.7 on 2024-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_polygonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.FloatField(default=0, null=True),
        ),
    ]
