# Generated by Django 5.0.1 on 2024-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nodepolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodePolygon',
        ),
    ]
