# Generated by Django 5.0.2 on 2024-05-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_nodepolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='node',
        ),
        migrations.DeleteModel(
            name='polygon',
        ),
    ]
